version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4079:4079"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_WEB_SERVER_URL=http://localhost:4079
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:4041/api
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next